variables:
  buildConfiguration: 'Release'

jobs:
- job: Test
  steps:
  - script: dotnet restore
    displayName: 'Restore'

  - script: dotnet build --no-restore --configuration $(buildConfiguration)
    displayName: 'Build'

  - script: dotnet test tests/HttpClient.Extensions.Tests --no-build --configuration $(buildConfiguration) --logger trx
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
    condition: succeededOrFailed()


- job: Pack
  dependsOn: Test
  condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/'))
  steps:
  - script: dotnet pack --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY /p:Version=$(Build.SourceBranchName)
    displayName: 'Pack'
  
  - task: PublishBuildArtifacts@1